[manifest]
id = "thrustr.dark"
name = "Dark"
authors = ["Jorge Pardo"]
version = "1.0.0"
description = "The default dark theme for Thrustr."

[colors]
background = "#0A0A0A"
sidebar_background = "#0A0A0A"
sidebar_foreground_primary = "#FFFFFF"
sidebar_foreground_secondary = "#646464"
sidebar_highlight = "#262626"
border = "#323232"
logo = "#B6B6B6"
