[manifest]
id = "thrustr.dark"
name = "Dark"
authors = ["Jorge Pardo"]
version = "1.0.0"
description = "The default dark theme for Thrustr."

[colors]
background = "#000000"

sidebar_background = "#000000"

border = "#373737"
