// THIS FILE WAS GENERATED BY `xtp-rust-bindgen`. DO NOT EDIT.

#![allow(non_snake_case)]
#![allow(unused_macros)]
use extism_pdk::*;

#[allow(unused)]
fn panic_if_key_missing() -> ! {
    panic!("missing key");
}

pub(crate) mod internal {
    pub(crate) fn return_error(e: extism_pdk::Error) -> i32 {
        let err = format!("{:?}", e);
        let mem = extism_pdk::Memory::from_bytes(&err).unwrap();
        unsafe {
            extism_pdk::extism::error_set(mem.offset());
        }
        -1
    }
}

#[allow(unused)]
macro_rules! try_input {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(x) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

#[allow(unused)]
macro_rules! try_input_json {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(extism_pdk::Json(x)) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

use base64_serde::base64_serde_type;

base64_serde_type!(Base64Standard, base64::engine::general_purpose::STANDARD);

mod exports {
    use super::*;

    #[no_mangle]
    pub extern "C" fn manifest() -> i32 {
        let ret = crate::manifest().and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }
}

pub mod types {
    use super::*;

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct Manifest {
        /// List of plugin authors
        #[serde(rename = "authors")]
        pub authors: Vec<String>,

        /// Brief description of the plugin
        #[serde(rename = "description")]
        pub description: String,

        /// Unique plugin identifier
        #[serde(rename = "id")]
        pub id: String,

        /// Human-readable plugin name
        #[serde(rename = "name")]
        pub name: String,

        /// Semantic version string (semver)
        #[serde(rename = "version")]
        pub version: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct SetPluginDataInput {
        /// The plugin data to set
        #[serde(rename = "data")]
        pub data: serde_json::Map<String, serde_json::Value>,

        /// Unique plugin identifier
        #[serde(rename = "id")]
        pub id: String,
    }
}

mod raw_imports {
    use super::*;
    #[host_fn]
    extern "ExtismHost" {

        pub(crate) fn get_plugin_data(
            input: String,
        ) -> Json<serde_json::Map<String, serde_json::Value>>;

        pub(crate) fn set_plugin_data(input: Json<types::SetPluginDataInput>) -> bool;

    }
}

/// get_plugin_data Retrieves plugin data from the host database.
/// It takes input of String (The plugin identifier.)
/// And it returns an output serde_json::Map<String, serde_json::Value> (The plugin data object.)
#[allow(unused)]
pub(crate) fn get_plugin_data(
    input: String,
) -> std::result::Result<serde_json::Map<String, serde_json::Value>, extism_pdk::Error> {
    let res = unsafe { raw_imports::get_plugin_data(input)? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// set_plugin_data Sets plugin data in the host database.
/// It takes input of types::SetPluginDataInput ()
/// And it returns an output bool (True if the operation was successful.)
#[allow(unused)]
pub(crate) fn set_plugin_data(
    input: types::SetPluginDataInput,
) -> std::result::Result<bool, extism_pdk::Error> {
    let res = unsafe { raw_imports::set_plugin_data(extism_pdk::Json(input))? };

    Ok(res)
}
