package thrustr:plugin@0.1.0;

interface base {
    use types.{error};

    init: func() -> result<_, error>;
    get-auth-url: func() -> result<option<string>, error>;
    validate-config: func(fields: list<tuple<string, string>>) -> result<_, error>;
}

world base-plugin {
    import config;
    import kv-store;

    export base;
}
