package thrustr:plugin@0.1.0;

interface storefront-provider {
    use types.{error};

    test: func() -> result<_, error>;
}

world storefront-provider-plugin {
    include base-plugin;

    export storefront-provider;
}
