package thrustr:plugin@0.1.0;

interface storefront-provider {
    variant error {
        not-autorized(string),
        other(string),
    }

    init: func() -> result<_, error>;
}

world storefront {
    import config;
    import kv-store;

    export storefront-provider;
}
