[package]
name = "plugin"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
# Local
component.workspace = true
config.workspace = true
domain.workspace = true
event.workspace = true
runtime.workspace = true

# External
anyhow.workspace = true
async-trait.workspace = true
blake3.workspace = true
bytes.workspace = true
dashmap.workspace = true
futures.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
hyper.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
wasmtime = "49"
wasmtime-wasi = "49"
wasmtime-wasi-http = "49"
zip.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
wiremock.workspace = true
