package thrustr:plugin@0.1.0;

interface kv-store {
    use types.{error};

    get: func(key: string) -> result<option<list<u8>>, error>;
    set: func(key: string, value: list<u8>) -> result<_, error>;
    delete: func(key: string) -> result<_, error>;
    %list: func(prefix: option<string>) -> result<list<string>, error>;
}
