package thrustr:plugin@0.1.0;

interface base {
    use types.{error};

    record auth-flow {
        url: string,
        target: string,
    }

    init: async func() -> result<_, error>;
    get-login-flow: async func() -> result<option<auth-flow>, error>;
    get-logout-flow: async func() -> result<option<auth-flow>, error>;
    login: async func(url: option<string>, body: option<string>, fields: option<list<tuple<string, string>>>) -> result<_, error>;
    logout: async func() -> result<_, error>;
    validate-config: async func(fields: list<tuple<string, string>>) -> result<_, error>;
}

world base-plugin {
    import config;
    import kv-store;

    export base;
}
