package thrustr:plugin@0.1.0;

interface storefront {
    use types.{error, game, game-version};

    get-games: async func() -> result<list<game>, error>;
    get-game-versions: async func(game: game) -> result<list<game-version>, error>;
}

world storefront-plugin {
    include base-plugin;

    export storefront;
}
