package thrustr:plugin@0.1.0;

interface storefront {
    use types.{error, game};

    list-games: func() -> result<list<game>, error>;
}

world storefront-plugin {
    include base-plugin;

    export storefront;
}
