package thrustr:plugin@0.1.0;

interface types {
    variant error {
        config(string),
        auth(string),
        other(string),
    }

    enum platform {
        windows,
        linux,
        macos,
    }

    record game {
        name: string,
        lookup-id: string,
        external-ids: list<tuple<string, string>>,
        cover-url: option<string>,
        description: option<string>,
    }

    record game-version {
        id: string,
        pretty-name: option<string>,
        platform: platform,
    }
}
